---
name: Java CI
on: [push, pull_request]
# Ensures that only a single workflow in the same concurrency group will run at the same time.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11.0.6'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          # Publish a Gradle build scan so you can see all the build logs,
          # a complete task timeline, test outputs, and the resolved dependencies of your build.
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Check Env Variables
        run: env
      - name: Check current working directory
        run: pwd
      
